services:
  - type: web
    name: store-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn store.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: store.settings
      - key: SECRET_KEY
        value: your_secret_key_here
