# Generated by Django 5.1.7 on 2025-04-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Store Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freshmart.store', verbose_name='Store')),
            ],
        ),
    ]
